import turtle			
ht = turtle.Turtle()
ht.color('red')
style = ('Courier', 90, 'normal')
ht.write('Anjali', font=style, align='center')
ht.penup()
ht.goto(0,-280)
ht.pendown()
ht.speed(1)
ht.begin_fill()
ht.fillcolor("red")
ht.left(140)
ht.forward(180)
ht.circle(-90,200)
ht.left(120)
ht.circle(-90,200)
ht.forward(180)
ht.end_fill()
ht.penup()
ht.goto(0,-400)
ht.pendown()
ht.write("I love you", font=style, align='center')
turtle.hideturtle()	
turtle.done()